### ISSUE TITLE
[FR] Control HA from Garmin Watch

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#86]
Utilise Garmin. Watch as controller for HA Entities

<details>
  <summary>Instructions</summary>

**Instructions**

- Click the search tab and type in HassControl
- Click on the widget and install it
- Open the widget setting 
- Under Host, enter your Home Assistant URL
- Note: Only a secure HTTPS connection is allowed, this limitation is imposed by Garmin.
- (Optional): If you want to use a long-lived access token instead of logging in, you can paste it here
- Under scenes, enter any scene you want controllable through the widget
- Scene setup is explained in detail bellow.
- Under group, enter group name to import entities to the widget
- Group setup is explained in detail bellow.
- To login to you HA instance, open the widget on your smart watch and trigger any scene/entity
- You will see a login request pop-up on your smartphone. Enter your credentials and login in to you HA server
- If you see a “No entities configured” screen press and hold the widget, click Settings and Refresh Entities.
- Done, now you can control your lights and switches  

**Config**

```
#Add this to your configuration.yaml
groups:
  garmin_lights:
    name: Lights
    entities:
      - light.sonoff_kitchen_led
      - light.sonoff_element_lights
      - light.bar_lights
      - light.sonoff_living_room
      - light.sonoff_wall_1
      - light.sonoff_wall_2
      - light.sonoff_wall_3
```

</details>
